config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'


  resources :contacts do
    resources :addresses
    resources :phones

    member do
      get 'message'
      post 'send_message'
    end

    collection do
      get 'over50s'
      get 'males'
      get 'females'
    end
  end

  get '/search', to: 'search#contacts', as: :search_contacts
  get '/advanced_search', to: 'search#advanced_contacts', as: :search_advanced_contacts
  get '/ransack', to: 'search#ransack', as: :search_ransack_contacts
end

app/models/search_form.rb
class SearchForm
  include ActiveModel::Model

  attr_accessor :q #Generic NAME Search

  validates_length_of :q, minimum: 2, message: 'At least 2 letters'

  def persisted?
    false
  end

  def search scope, column_name
    unless self.q.blank?
      scope = scope.where(column_name => self.q)
    end
    scope
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  skip_before_filter :verify_authenticity_token

  def pagination_page_size
    4 # Because we display full data
  end

  def contacts
    @search_form = SearchForm.new(search_params)

    gon.search_params = search_params

    if (@search_form.valid?)
      @contacts = prep_pagination @search_form.search Contact.all, :first_name
    end
  end

  def advanced_contacts
    @advanced_search_form = AdvancedSearchForm.new(advanced_search_params)
    if (@advanced_search_form.valid?)
      @advanced_search_form.preload_phones = true
      @advanced_search_form.preload_addresses = true
      @contacts = prep_pagination @advanced_search_form.get_contacts
    end
  end

  def ransack
    @search = Contact.search(params[:q])
    @contacts = prep_pagination(@search.result, 10)

    # Only required if we are using the complex form
    @search.build_condition

    # Only required if we are using sorting
    @search.build_sort if @search.sorts.empty?
  end

  private
  def advanced_search_params
    if (params.has_key? :advanced)
      # I would like to put this in the AdvancedSearchForm class but left it here to be clearer
      params.require(:advanced).permit(:last_name, :first_name, :zip, :phone, :sorting)
    end
  end

  def search_params
    if (params.has_key? :search_form)
      # I would like to put this in the SearchForm class but left it here to be clearer
      params.require(:search_form).permit(:q)
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_contacts_results.html.erb
<% unless contacts.blank? %>

    <div>
      <%= paginate contacts, :theme => 'twitter-bootstrap-3' %>
    </div>

    <div class="contacts">
      <% contacts.each do |contact| %>
          <div class="contact <%= contact_card_class contact %>">
            <div class="caption">
              <h3><%= link_to contact.full_name, edit_contact_path(contact) %></h3>
            </div>
            <div class="row">
              <div class="col-sm-6 col-md-6">
                <%= render partial: 'phones/cards', locals: {phones: contact.phones} %>
              </div>
              <div class="col-sm-6 col-md-6">
                <%= render partial: 'addresses/cards', locals: {addresses: contact.addresses} %>
              </div>
            </div>
          </div>
      <% end %>
    </div>

    <div>
      <%= paginate contacts, :theme => 'twitter-bootstrap-3' %>
    </div>

<% else %>
    <div>There are no contacts matching your search</div>
<% end %>

app/views/search/advanced_contacts.html.erb
<div class="page-header">
  <h1>Advanced <span class="hidden-xs">Contacts</span> Search</h1>
</div>

<%= simple_form_for(@advanced_search_form, url: search_advanced_contacts_path, as: :advanced, method: :get, authenticity_token: false,
                    html: {class: 'form-inline addressbook-inline clearfix'},
                    wrapper: :inline_form,
                    wrapper_mappings: {}) do |f| %>

    <%= f.input :first_name, class: 'form-control', placeholder: 'First Name', label: false %>
    <%= f.input :last_name, class: 'form-control', placeholder: 'Last Name', label: false %>
    <%= f.input :zip, class: 'form-control', placeholder: 'Zipcode', label: false %>
    <%= f.input :phone, class: 'form-control', placeholder: 'Phone', label: false %>
    <%= f.input :sorting, collection: {'Sort By...' => '', 'Oldest' => 'oldest', 'Youngest' => 'youngest'}, class: "form-control", include_blank: false, label: false %>
    <div class="form-group col-xs-12 col-sm-2 col-md-2">
      <%= f.button :button, class: 'form-control' do %>
          <i class="glyphicon glyphicon-search"></i>
      <% end %>
    </div>
<% end %>

<div class="well">
  <%= link_to search_ransack_contacts_path do %>
      <span class="hidden-xs">Need Even More Tools? - </span>Try Our Ransack Search
  <% end %>
</div>

<%= render partial: 'contacts_results', locals: {contacts: @contacts} %>

app/views/search/contacts.html.erb
<div class="page-header">
  <h1><span class="hidden-xs">Search</span> Results for <i><%= @search_form.q %></i></h1>
</div>

<div class="well">
  <%= link_to search_advanced_contacts_path do %>
      <span class="hidden-xs">Need More Tools? - </span>Try Our Advanced Search
  <% end %>
</div>

<%= render partial: 'contacts_results', locals: {contacts: @contacts} %>

app/views/search/ransack.html.erb
<div class="page-header">
  <h1>Ransack <span class="hidden-xs">Search</span></h1>
</div>

<%= search_form_for @search, url: search_ransack_contacts_path do |f| %>
    <%= f.condition_fields do |c| %>
        <div class="row">
          <div class="form-group col-xs-4">
            <%= c.attribute_fields do |a| %>
                <%= a.attribute_select({associations: [:addresses, :phones]}, {:class => 'form-control'}) %>
            <% end %>
          </div>
          <div class="form-group col-xs-4">
            <%= c.predicate_select({compounds: false, only: [:cont, :not_cont, :eq, :not_eq, :blank, :null, :not_null]}, {:class => 'form-control'}) %>
          </div>
          <div class="form-group col-xs-4">
            <%= c.value_fields do |v| %>
                <%= v.text_field :value, :class => "form-control input-medium search-field" %>
            <% end %>
          </div>
        </div>
    <% end %>
    <div class="row">
      <%= f.sort_fields do |s| %>
          <div class="form-group col-xs-4">
            <%= s.attribute_select({}, {:class => 'form-control'}, 'sort') %>
          </div>
          <div class="form-group col-xs-4">
            <%= s.sort_direction_select({}, {:class => 'form-control'},) %>
          </div>
      <% end %>
      <div class="form-group col-xs-4">
        <%= f.button class: 'btn btn-default' do %>
            <i class="glyphicon glyphicon-search"></i> Search
        <% end %>
      </div>
    </div>
<% end %>

<div>
  <%= paginate @contacts, :theme => 'twitter-bootstrap-3' %>
</div>

<table class="table">
  <tr>
    <th><%= sort_link(@search, :first_name, "First Name") %></th>
    <th><%= sort_link(@search, :last_name, "First Name") %></th>
    <th><%= sort_link(@search, :dob, "Birth Date") %></th>
  </tr>
  <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.dob %></td>
      </tr>
  <% end %>
</table>

app/views/search/search_contacts.html.erb
<div class="page-header">
  <h1>Search Contacts</h1>
</div>


<%= form_for(@search_form, url: advanced_search_path, authenticity_token: false, html: {class: "form-inline addressbook-inline"}) do |f| %>
    <% if @search_form.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @search_form.errors.each do |field, message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">
      <%= f.text_field :q, class: 'form-control', placeholder: 'Name' %>
    </div>
    <div class="form-group">
      <%= f.button 'Search', class: 'btn btn-primary' %>
    </div>
<% end %>

<% unless @contacts.blank? %>
    <div class="row">
      <% @contacts.each do |contact| %>

          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <div class="caption">
                <h3><%= link_to contact.full_name, contact %></h3>
              </div>
              <div class="addressbook-card clearfix">
                <%= render partial: 'phones/cards', locals: {phones: contact.phones} %>
                <%= render partial: 'addresses/cards', locals: {addresses: contact.addresses} %>
                <div class="pull-right">
                  <%= link_to('Show', contact_path(contact), {class: 'btn btn-default'}) %>
                  <%= link_to('Edit', edit_contact_path(contact), {class: 'btn btn-default'}) %>
                </div>

              </div>
            </div>
          </div>
      <% end %>
    </div>
    <div>
      <%= paginate @contacts, :theme => 'twitter-bootstrap-3' %>
    </div>
<% else %>
    <div>There are no contacts matching your search</div>
<% end %>