config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'


  resources :contacts do
    resources :addresses
    resources :phones

    member do
      get 'message'
      post 'send_message'
    end

    collection do
      get 'over50s'
      get 'males'
      get 'females'
    end
  end

  get '/search', to: 'search#contacts', as: :search_contacts
  get '/advanced_search', to: 'search#advanced_contacts', as: :search_advanced_contacts
  get '/ransack', to: 'search#ransack', as: :search_ransack_contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  GENDER_MALE = 1
  GENDER_FEMALE = 2

  scope :males, ->{ where(gender: GENDER_MALE ) }
  scope :females, ->{ where(gender: GENDER_FEMALE ) }

  validates_inclusion_of :gender, in: [nil, GENDER_MALE, GENDER_FEMALE], message: 'Please select either Male or Female'
  validates_presence_of :first_name, message: 'Please enter a name'

  validates :email, :presence => false, :email => true

  def messaging_possible?
    MessageForm.messaging_enabled && !self.email.blank?
  end

  has_many :addresses
  has_many :phones
  def full_name
    "#{first_name} #{last_name}"
  end

  #
  # def self.ransackable_attributes(auth_object = nil)
  #   [:first_name, :last_name]
  # end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy, :message, :send_message]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = prep_pagination Contact.all
  end

  def over50s
    @today = Time.now
    @then = @today - 50.years
    @contacts = prep_pagination Contact.where('dob < :then', {then: @then})
    @filter_label = 'Over 50\'s'
    render 'filtered'
  end

  def males
    @contacts = prep_pagination Contact.where(gender: Contact::GENDER_MALE)
    @filter_label = 'Males'
    render 'filtered'
  end

  def females
    @contacts = prep_pagination Contact.females
    @filter_label = 'Females'
    render 'filtered'
  end

  # GET /contacts/1/message
  def message
    redirect_to edit_contact_path(@contact), notice: 'Messaging Disabled' unless @contact.messaging_possible?
    @message_form = MessageForm.new
    @message_form.contact = @contact
  end

  # POST /contacts/1/send_message
  def send_message
    redirect_to edit_contact_path(@contact), notice: 'Messaging Disabled' unless @contact.messaging_possible?
    @message_form = MessageForm.new message_params
    @message_form.contact = @contact
    if @message_form.valid? && @message_form.send_message
      redirect_to edit_contact_path(@contact), notice: 'Message Sent'
    else
      render 'message'
    end
  end


  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to edit_contact_path(@contact), notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to edit_contact_path(@contact), notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  # def destroy
  #   @contact.destroy
  #   respond_to do |format|
  #     format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :dob, :gender, :email)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message_form).permit(:message_subject, :message_body)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper

  def contacts_for_select
    Contact.all.collect { |m| [m.full_name, m.id] }
  end

  def contact_gender_display contact
    if contact.gender == Contact::GENDER_MALE
      'Male'
    elsif contact.gender == Contact::GENDER_FEMALE
      'Female'
    end
  end

  def contact_card_class contact
    if contact.gender == Contact::GENDER_MALE
      'addressbook-male'
    elsif contact.gender == Contact::GENDER_FEMALE
      'addressbook-female'
    end
  end
end

app/views/contacts/_contacts_table.html.erb
<ul class="nav nav-tabs">
  <li class="<%= 'active' if current_page?(contacts_path) %>"><%= link_to "All", contacts_path %></li>
  <li class="<%= 'active' if current_page?(over50s_contacts_path) %>"><%= link_to "Over 50's", over50s_contacts_path %></li>
  <li class="<%= 'active' if current_page?(males_contacts_path) %>"><%= link_to "Male", males_contacts_path %></li>
  <li class="<%= 'active' if current_page?(females_contacts_path) %>"><%= link_to "Female", females_contacts_path %></li>
</ul>

<div>
  <%= paginate contacts, :theme => 'twitter-bootstrap-3' %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Name</th>
      <th class="hidden-xs">Gender</th>
      <th>Date of Birth</th>
    </tr>
    </thead>

    <tbody>
    <% contacts.each do |contact| %>
        <tr class="<%= contact_card_class contact %>">
          <td><%= link_to contact.full_name, edit_contact_path(contact) %></td>
          <td class="hidden-xs"><%= contact_gender_display contact %></td>
          <td><%= contact.dob %> <span class="hidden-xs">(<%= distance_of_time_in_words_to_now contact.dob if contact.dob%> ago)</span></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div>
  <%= paginate contacts, :theme => 'twitter-bootstrap-3' %>
</div>

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact,
                    html: {class: 'form-horizontal'},
                    wrapper: :horizontal_form,
                    wrapper_mappings: {check_boxes: :horizontal_radio_and_checkboxes,
                                       radio_buttons: :horizontal_radio_and_checkboxes,
                                       file: :horizontal_file_input,
                                       boolean: :horizontal_boolean}) do |f| %>
    <%= f.error_notification %>
    <%= f.input :first_name, placeholder: 'First Name' %>
    <%= f.input :last_name, placeholder: 'Last Name' %>
    <%= f.input :email, placeholder: 'Email' %>
    <%= f.input :dob,:as => :string  %>
    <%= f.input :gender, label: 'Gender', collection: [ [Contact::GENDER_MALE, 'Male' ], [Contact::GENDER_FEMALE, 'Female'] ], as: :radio_buttons, label_method: :last, value_method: :first, checked: @contact.gender, item_wrapper_class: 'inline' %>
    <%= f.button :submit  %>

<% end %>

app/views/contacts/edit.html.erb
<div class="addressbook-commands"></div>
<%= render 'form' %>

app/views/contacts/filtered.html.erb
<div class="page-header">
  <h1>Contacts: <%= @filter_label %></h1>
</div>
<%= render partial: 'contacts_table', locals: {contacts: @contacts} %>

<div>
  <%= link_to new_contact_path, :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      Add Contact
  <% end %>
</div>

app/views/contacts/index.html.erb
<div class="page-header">
  <h1>All Contacts</h1>
</div>



<%= render partial: 'contacts_table', locals: {contacts: @contacts} %>

app/views/contacts/message.html.erb
<div class="addressbook-commands"></div>

<%= simple_form_for(@message_form,
                    url: send_message_contact_path(@message_form.contact),
                    html: {class: 'form-horizontal'},
                    wrapper: :horizontal_form,
                    wrapper_mappings: {check_boxes: :horizontal_radio_and_checkboxes,
                                       radio_buttons: :horizontal_radio_and_checkboxes,
                                       file: :horizontal_file_input,
                                       boolean: :horizontal_boolean}) do |f| %>
    <%= f.error_notification %>
    <%= f.input :message_subject, class: 'form-control', placeholder: 'Subject',  label: 'Subject', :as => :string %>
    <%= f.input :message_body, placeholder: 'Message', label: 'Message', :as => :text %>
    <%= f.button :button do %>
        Send!
    <% end %>
<% end %>

app/views/contacts/new.html.erb
<h1>Add Contact</h1>

<%= render 'form' %>

app/views/contacts/over50s.html.erb
<div class="page-header">
  <h1>Contacts: Over 50's</h1>
</div>
<%= render partial: 'contacts_table', locals: {contacts: @contacts} %>

<div>
  <%= link_to new_contact_path, :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      Add Contact
  <% end %>
</div>