config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'


  resources :contacts do
    resources :addresses
    resources :phones

    member do
      get 'message'
      post 'send_message'
    end

    collection do
      get 'over50s'
      get 'males'
      get 'females'
    end
  end

  get '/search', to: 'search#contacts', as: :search_contacts
  get '/advanced_search', to: 'search#advanced_contacts', as: :search_advanced_contacts
  get '/ransack', to: 'search#ransack', as: :search_ransack_contacts
end

app/controllers/addresses_controller.rb
class AddressesController < BelongsToContactController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = prep_pagination @contact.addresses
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = @contact.addresses.build
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = @contact.addresses.build(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to contact_addresses_path(@contact), notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to contact_addresses_path(@contact), notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  # def destroy
  #   @address.destroy
  #   respond_to do |format|
  #     format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_address
    @address = @contact.addresses.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def address_params
    params.require(:address).permit(:address_type, :street, :street_2, :city, :state, :zip)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper

end

app/views/addresses/_cards.html.erb
<% unless addresses.blank? %>
    <div class="addresses-card">
      <div class="addresses-header">Addresses</div>
      <table class="table table-striped">
        <% addresses.each do |address| %>
            <tr>
              <td><%= contact_type_icon address.address_type %></td>
              <td>
                <span class="street"><%= address.street %></span>
                <span class="street_2"><%= address.street_2 %></span>
                <br/>
                <span class="city"><%= address.city %></span>
                <span class="state"><%= address.state %></span>
                <span class="zip"><%= address.zip %></span>
              </td>
              <td align="right">
                <%= link_to('Edit', edit_contact_address_path(address.contact, address)) %>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
<% end %>

app/views/addresses/_form.html.erb
<%= simple_form_for([@contact, @address],
                    html: {class: 'form-horizontal'},
                    wrapper: :horizontal_form,
                    wrapper_mappings: {check_boxes: :horizontal_radio_and_checkboxes,
                                       radio_buttons: :horizontal_radio_and_checkboxes,
                                       file: :horizontal_file_input,
                                       boolean: :horizontal_boolean}) do |f| %>
    <%= f.error_notification %>
    <%= f.input :street, placeholder: 'Number and Street' %>
    <%= f.input :street_2, placeholder: 'Suite or Apt' %>
    <%= f.input :city, placeholder: 'City' %>
    <%= f.input :state, placeholder: 'State' %>
    <%= f.input :zip, placeholder: 'Zipcode' %>
    <%= contact_type_field f, @address, :address_type %>
    <%= f.button :submit  %>

<% end %>

app/views/addresses/edit.html.erb
<h1>Edit Address</h1>

<%= render 'form' %>

app/views/addresses/index.html.erb
<div class="addressbook-commands">
<%= link_to_unless_current raw("<span class='glyphicon glyphicon-plus'></span> Add Address for #{@contact.full_name}"), new_contact_address_path(@contact), :class => 'btn btn-default' %>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th class="addressbook-type"></th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @addresses.each do |address| %>
        <tr class="contact_type_<%= address.address_type %>">
          <td><%= contact_type_icon address.address_type %></td>
          <td><%= address.street %>
            <% unless address.street_2.blank? %>
                &nbsp;
                <small>(<%= address.street_2 %>)</small>
            <% end %>
          </td>
          <td><%= address.city %></td>
          <td><%= address.state %></td>
          <td><%= address.zip %></td>
          <td><%= link_to 'Edit', edit_contact_address_path(@contact, address) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div>
  <%= paginate @addresses, :theme => 'twitter-bootstrap-3' %>
</div>
<div>

</div>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>