config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'


  resources :contacts do
    resources :addresses
    resources :phones

    member do
      get 'message'
      post 'send_message'
    end

    collection do
      get 'over50s'
      get 'males'
      get 'females'
    end
  end

  get '/search', to: 'search#contacts', as: :search_contacts
  get '/advanced_search', to: 'search#advanced_contacts', as: :search_advanced_contacts
  get '/ransack', to: 'search#ransack', as: :search_ransack_contacts
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Addressbook</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">AddressBook</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to search_advanced_contacts_path do %>
              <i class="glyphicon glyphicon-search"></i> Adv
          <% end %>
        </li>
        <li>
          <%= link_to new_contact_path do %>
              <i class="glyphicon glyphicon-plus"></i> Contact
          <% end %>
        </li>
      </ul>
      <%= form_for(SearchForm.new(search_form_parameters), url: search_contacts_path, method: :get, authenticity_token: false, html: {class: "navbar-form"}) do |f| %>
          <div class="input-group">
            <%= f.text_field :q, class: 'form-control', placeholder: 'Name Search' %>
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
          </div>
      <% end %>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

<div class="container">
  <% if @contact && @contact.persisted? %>
      <div class="page-header">
        <h1><%= @contact.full_name %></h1>
      </div>
      <ul class="nav nav-tabs">
        <li class="<%= 'active' if current_page?(edit_contact_path @contact) %>"><%= link_to "Edit", edit_contact_path(@contact) %></li>
        <li class="<%= 'active' if current_page?(contact_addresses_path(@contact)) %>"><%= link_to "Addresses", contact_addresses_path(@contact) %></li>
        <li class="<%= 'active' if current_page?(contact_phones_path(@contact)) %>"><%= link_to "Phone Numbers", contact_phones_path(@contact) %></li>
        <% if @contact.messaging_possible? %>
            <li class="<%= 'active' if current_page?(message_contact_path(@contact)) %>"><%= link_to "Send Message", message_contact_path(@contact) %></li>
        <% end %>
      </ul>
  <% end %>

  <%= yield %>

  <div class="addressbook-debugging panel panel-default">
    <% if @pagintation_scopes %>
        <div class="panel-heading">Debugging SQL</div>
        <div class="panel-panel">
          <% @pagintation_scopes.each do |scope| %>
<pre>
  <%= scope.to_sql %>
</pre>
          <% end %>

        </div>
    <% end %>
    <div class="panel-heading">Verison Info</div>
    <div class="panel-panel">
      <table class="table">
        <tr>
          <td>Branch</td>
          <td><%= Stujo::Git.current_branch %></td>
        </tr>
        <tr>
          <td>Timestamp</td>
          <td><%= Stujo::Git.current_timestamp %> (<%= time_ago_in_words Time.at(Stujo::Git.current_timestamp) %>)</td>
        </tr>
      </table>
    </div>
  </div>
</div>
</div>
</body>
</html>